language: java
jdk:
  - openjdk14

sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vasyl.byalyk@gmail.com
    on_success: never # default: change
<<<<<<< HEAD
    on_failure: always # default: always
=======
    on_failure: always # default: always
>>>>>>> 2b72eff25aa69d85c12931a288351f9418db861a
