language: java
jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="198f203c-3bb8-48ee-9fef-521228a40660"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vasyl.byalyk@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
